// Tabela INMETRO/PBE — Coletor Solar (Aplicação Banho). Fonte: PDF oficial do cliente (versão 16/12/2025).
// Gerado automaticamente a partir do PDF. Usado no seletor fabricante/marca → modelo do módulo Caixa/Solar.
export interface Coletor {
  marca: string;
  modelo: string;
  fornecedor: string;
  producao: number; // kWh/mês por coletor (campo "Por Coletor")
  eficiencia: number; // % eficiência energética média
  classificacao: string; // A..E (PBE)
  area: number; // m²
}

export const COLETORES: Coletor[] = [
  {marca:"A Atual",modelo:"MASTER 2.0",fornecedor:"A Atual Ind. e Com. de Aquecedores Solares Ltda.",producao:159.5,eficiencia:61.1,classificacao:"A",area:1.9},
  {marca:"A Atual",modelo:"STANDARD 1.3",fornecedor:"A Atual Ind. e Com. de Aquecedores Solares Ltda.",producao:110.2,eficiencia:65.3,classificacao:"A",area:1.2},
  {marca:"A Atual",modelo:"STANDARD 2.0",fornecedor:"A Atual Ind. e Com. de Aquecedores Solares Ltda.",producao:164.2,eficiencia:65.3,classificacao:"A",area:1.8},
  {marca:"AQUAKENT",modelo:"AKC 25E",fornecedor:"Aquakent Indústria e Comércio Ltda.",producao:299.9,eficiencia:70.5,classificacao:"B",area:3.8},
  {marca:"AQUAKENT",modelo:"AKC 25L",fornecedor:"Aquakent Indústria e Comércio Ltda.",producao:274.9,eficiencia:70.5,classificacao:"B",area:3.5},
  {marca:"AQUAKENT",modelo:"AKP 20",fornecedor:"Aquakent Indústria e Comércio Ltda.",producao:240.3,eficiencia:71.1,classificacao:"B",area:3.1},
  {marca:"AQUAKENT",modelo:"AKP 30",fornecedor:"Aquakent Indústria e Comércio Ltda.",producao:352.3,eficiencia:71.1,classificacao:"B",area:4.5},
  {marca:"AQUAKENT",modelo:"AKPP2",fornecedor:"Aquakent Indústria e Comércio Ltda.",producao:158.9,eficiencia:58.7,classificacao:"B",area:2.0},
  {marca:"AQUESOL",modelo:"COLETOR SOLAR DE 15 TUBOS BP",fornecedor:"Aquesol Indústria Aquecimento Solar Ltda.",producao:157.4,eficiencia:54.6,classificacao:"B",area:2.1},
  {marca:"AQUESOL",modelo:"COLETOR SOLAR DE 20 TUBOS BP",fornecedor:"Aquesol Indústria Aquecimento Solar Ltda.",producao:223.7,eficiencia:54.6,classificacao:"B",area:3.0},
  {marca:"AQUESOL",modelo:"COLETOR SOLAR DE 25 TUBOS BP",fornecedor:"Aquesol Indústria Aquecimento Solar Ltda.",producao:279.3,eficiencia:54.6,classificacao:"B",area:3.8},
  {marca:"AQUESOL",modelo:"COLETOR SOLAR DE 30 TUBOS BP",fornecedor:"Aquesol Indústria Aquecimento Solar Ltda.",producao:332.0,eficiencia:54.6,classificacao:"B",area:4.5},
  {marca:"AQUESOL",modelo:"COLETOR SOLAR DE 30 TUBOS EP",fornecedor:"Aquesol Indústria Aquecimento Solar Ltda.",producao:287.8,eficiencia:56.8,classificacao:"C",area:4.3},
  {marca:"AQUESOL",modelo:"COLETOR SOLAR DE 40 TUBOS EP",fornecedor:"Aquesol Indústria Aquecimento Solar Ltda.",producao:397.2,eficiencia:56.8,classificacao:"C",area:5.9},
  {marca:"AQUESOL",modelo:"COLETOR SOLAR DE 50 TUBOS EP",fornecedor:"Aquesol Indústria Aquecimento Solar Ltda.",producao:490.3,eficiencia:56.8,classificacao:"C",area:7.3},
  {marca:"AQUESOL",modelo:"COLETOR SOLAR DE 60 TUBOS EP",fornecedor:"Aquesol Indústria Aquecimento Solar Ltda.",producao:585.8,eficiencia:56.8,classificacao:"C",area:8.8},
  {marca:"ARKSOL",modelo:"SATURNO2000H",fornecedor:"Arksol Indústria e Comércio Ltda.",producao:164.5,eficiencia:59.2,classificacao:"A",area:2.0},
  {marca:"ARKSOL",modelo:"SATURNO2000V",fornecedor:"Arksol Indústria e Comércio Ltda.",producao:164.5,eficiencia:59.2,classificacao:"A",area:2.0},
  {marca:"ASTRAL",modelo:"Inox Power – IP 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.0},
  {marca:"ASTRAL",modelo:"Inox Power – IP 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.5},
  {marca:"ASTRAL",modelo:"Inox Power – IP 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.7},
  {marca:"ASTRAL",modelo:"Inox Power – IP 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:2.0},
  {marca:"ASTRAL",modelo:"Ultra Supreme – US 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:102.3,eficiencia:72.6,classificacao:"A",area:1.0},
  {marca:"ASTRAL",modelo:"Ultra Supreme – US 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:153.3,eficiencia:72.6,classificacao:"A",area:1.5},
  {marca:"ASTRAL",modelo:"Ultra Supreme – US 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:173.8,eficiencia:72.6,classificacao:"A",area:1.7},
  {marca:"ASTRAL",modelo:"Ultra Supreme – US 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:204.5,eficiencia:72.6,classificacao:"A",area:2.0},
  {marca:"BERETTA",modelo:"SCF-20B",fornecedor:"Mantovani Materiais para Construção Ltda.",producao:191.6,eficiencia:74.6,classificacao:"A",area:1.9},
  {marca:"BERETTA",modelo:"SCF-25B",fornecedor:"Mantovani Materiais para Construção Ltda.",producao:229.8,eficiencia:73.8,classificacao:"A",area:2.3},
  {marca:"BERETTA",modelo:"SCO-25B",fornecedor:"Mantovani Materiais para Construção Ltda.",producao:229.8,eficiencia:73.8,classificacao:"A",area:2.3},
  {marca:"BROILO",modelo:"BNP-1-20",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:249.8,eficiencia:72.1,classificacao:"A",area:3.1},
  {marca:"BROILO",modelo:"BNP-1-30",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:366.1,eficiencia:72.1,classificacao:"A",area:4.5},
  {marca:"BROILO",modelo:"Ultra Supreme – US 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:102.3,eficiencia:72.6,classificacao:"A",area:1.0},
  {marca:"BROILO",modelo:"Ultra Supreme – US 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:153.3,eficiencia:72.6,classificacao:"A",area:1.5},
  {marca:"BROILO",modelo:"Ultra Supreme – US 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:173.8,eficiencia:72.6,classificacao:"A",area:1.7},
  {marca:"BROILO",modelo:"Ultra Supreme – US 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:204.5,eficiencia:72.6,classificacao:"A",area:2.0},
  {marca:"CENTER SOL",modelo:"CS CB 1,00 x 1,00",fornecedor:"Center Sol Com. e Ind. de Aquecedor Solar",producao:81.8,eficiencia:58.0,classificacao:"A",area:1.0},
  {marca:"CENTER SOL",modelo:"CS CB 1,50 x 1,00",fornecedor:"Center Sol Com. e Ind. de Aquecedor Solar",producao:122.5,eficiencia:58.0,classificacao:"A",area:1.5},
  {marca:"CENTER SOL",modelo:"CS CB 2,00 x 1,00",fornecedor:"Center Sol Com. e Ind. de Aquecedor Solar",producao:163.3,eficiencia:58.0,classificacao:"A",area:2.0},
  {marca:"CMAX",modelo:"CSCMAX15CU",fornecedor:"Solar Minas Ltda.",producao:134.3,eficiencia:64.2,classificacao:"A",area:1.5},
  {marca:"CMAX",modelo:"CSCMAX15CUSLIM",fornecedor:"Solar Minas Ltda.",producao:103.2,eficiencia:54.7,classificacao:"B",area:1.4},
  {marca:"CMAX",modelo:"CSCMAX15INPLUS",fornecedor:"Solar Minas Ltda.",producao:124.9,eficiencia:58.9,classificacao:"A",area:1.5},
  {marca:"CMAX",modelo:"CSCMAX20CU",fornecedor:"Solar Minas Ltda.",producao:180.2,eficiencia:64.2,classificacao:"A",area:2.0},
  {marca:"CMAX",modelo:"CSCMAX20CUSLIM",fornecedor:"Solar Minas Ltda.",producao:137.6,eficiencia:54.7,classificacao:"B",area:1.8},
  {marca:"CMAX",modelo:"CSCMAX20INPLUS",fornecedor:"Solar Minas Ltda.",producao:166.6,eficiencia:58.9,classificacao:"A",area:2.0},
  {marca:"COBERTURE",modelo:"Inox Power – IP 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.0},
  {marca:"COBERTURE",modelo:"Inox Power – IP 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.5},
  {marca:"COBERTURE",modelo:"Inox Power – IP 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.7},
  {marca:"COBERTURE",modelo:"Inox Power – IP 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:2.0},
  {marca:"COBERTURE",modelo:"Ultra Supreme – US 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:1.0},
  {marca:"COBERTURE",modelo:"Ultra Supreme – US 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:1.5},
  {marca:"COBERTURE",modelo:"Ultra Supreme – US 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:1.7},
  {marca:"COBERTURE",modelo:"Ultra Supreme – US 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:2.0},
  {marca:"CUMULUS",modelo:"Inox Power – IP 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.0},
  {marca:"CUMULUS",modelo:"Inox Power – IP 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.5},
  {marca:"CUMULUS",modelo:"Inox Power – IP 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.7},
  {marca:"CUMULUS",modelo:"Inox Power – IP 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:2.0},
  {marca:"CUMULUS",modelo:"Ultra Supreme – US 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:1.0},
  {marca:"CUMULUS",modelo:"Ultra Supreme – US 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:1.5},
  {marca:"CUMULUS",modelo:"Ultra Supreme – US 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:1.7},
  {marca:"CUMULUS",modelo:"Ultra Supreme – US 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:2.0},
  {marca:"ECOLOGIC",modelo:"BNP-1-15",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:189.4,eficiencia:72.1,classificacao:"A",area:2.3},
  {marca:"ECOLOGIC",modelo:"BNP-1-20",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:249.8,eficiencia:72.1,classificacao:"A",area:3.1},
  {marca:"ECOLOGIC",modelo:"BNP-1-25",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:308.0,eficiencia:72.1,classificacao:"A",area:3.8},
  {marca:"ECOLOGIC",modelo:"BNP-1-30",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:366.1,eficiencia:72.1,classificacao:"A",area:4.5},
  {marca:"ECOLOGIC",modelo:"BNP-1-30 H",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:319.0,eficiencia:63.1,classificacao:"C",area:4.6},
  {marca:"ECOLOGIC",modelo:"BNP-1-40 H",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:410.3,eficiencia:63.1,classificacao:"C",area:5.9},
  {marca:"ECOLOGIC",modelo:"BNP-1-50 H",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:509.0,eficiencia:63.1,classificacao:"C",area:7.3},
  {marca:"ECOLOGIC",modelo:"BNP-1-60 H",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:8.7,eficiencia:63.1,classificacao:"C",area:8.7},
  {marca:"ECOLOGIC",modelo:"BPS-1-20",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:253.5,eficiencia:72.6,classificacao:"A",area:2.9},
  {marca:"ECOLOGIC",modelo:"BPS-1-30",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:386.0,eficiencia:72.6,classificacao:"A",area:4.4},
  {marca:"ECOPRO",modelo:"BNP-1-15",fornecedor:"Ecopro Comércio Produtos Sustentáveis Ltda. EPP",producao:179.7,eficiencia:70.9,classificacao:"B",area:2.3},
  {marca:"ECOPRO",modelo:"BNP-1-20",fornecedor:"Ecopro Comércio Produtos Sustentáveis Ltda. EPP",producao:236.1,eficiencia:70.9,classificacao:"B",area:3.1},
  {marca:"ECOPRO",modelo:"BNP-1-25",fornecedor:"Ecopro Comércio Produtos Sustentáveis Ltda. EPP",producao:291.2,eficiencia:70.9,classificacao:"B",area:3.8},
  {marca:"ECOPRO",modelo:"CROMO15",fornecedor:"Ecopro Comércio Produtos Sustentáveis Ltda. EPP",producao:189.1,eficiencia:72.4,classificacao:"A",area:2.3},
  {marca:"ECOPRO",modelo:"CROMO20",fornecedor:"Ecopro Comércio Produtos Sustentáveis Ltda. EPP",producao:241.9,eficiencia:72.4,classificacao:"A",area:2.9},
  {marca:"ECOPRO",modelo:"CROMO25",fornecedor:"Ecopro Comércio Produtos Sustentáveis Ltda. EPP",producao:3.8,eficiencia:72.4,classificacao:"A",area:3.8},
  {marca:"ECOPRO",modelo:"CROMO30",fornecedor:"Ecopro Comércio Produtos Sustentáveis Ltda. EPP",producao:4.5,eficiencia:72.4,classificacao:"A",area:4.5},
  {marca:"ECOPRO SOLLIDER",modelo:"VULCANO 1.0V",fornecedor:"Ecopro Comércio Produtos Sustentáveis Ltda. EPP",producao:82.2,eficiencia:58.3,classificacao:"A",area:1.0},
  {marca:"ECOPRO SOLLIDER",modelo:"VULCANO 1.5V",fornecedor:"Ecopro Comércio Produtos Sustentáveis Ltda. EPP",producao:119.7,eficiencia:58.3,classificacao:"A",area:1.5},
  {marca:"ECOPRO SOLLIDER",modelo:"VULCANO 1.7V",fornecedor:"Ecopro Comércio Produtos Sustentáveis Ltda. EPP",producao:135.9,eficiencia:58.3,classificacao:"A",area:1.7},
  {marca:"ECOPRO SOLLIDER",modelo:"VULCANO 2.0V",fornecedor:"Ecopro Comércio Produtos Sustentáveis Ltda. EPP",producao:160.2,eficiencia:58.3,classificacao:"A",area:2.0},
  {marca:"ECOTHERMO",modelo:"15 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:188.8,eficiencia:77.2,classificacao:"A",area:2.3},
  {marca:"ECOTHERMO",modelo:"20 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:245.9,eficiencia:77.2,classificacao:"A",area:3.0},
  {marca:"ECOTHERMO",modelo:"25 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:307.1,eficiencia:77.2,classificacao:"A",area:3.8},
  {marca:"ECOTHERMO",modelo:"30 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:365.1,eficiencia:77.2,classificacao:"A",area:4.5},
  {marca:"ECOTHERMO LTDA",modelo:"COLETOR SOLAR 15 TUBOS BP",fornecedor:"Ecothermo Ltda.",producao:192.6,eficiencia:69.7,classificacao:"A",area:2.3},
  {marca:"ECOTHERMO LTDA",modelo:"COLETOR SOLAR 20 TUBOS BP",fornecedor:"Ecothermo Ltda.",producao:252.8,eficiencia:69.7,classificacao:"A",area:3.0},
  {marca:"ECOTHERMO LTDA",modelo:"COLETOR SOLAR 25 TUBOS BP",fornecedor:"Ecothermo Ltda.",producao:306.9,eficiencia:69.7,classificacao:"A",area:3.7},
  {marca:"ECOTHERMO LTDA",modelo:"COLETOR SOLAR 30 TUBOS BP",fornecedor:"Ecothermo Ltda.",producao:386.7,eficiencia:69.7,classificacao:"A",area:4.7},
  {marca:"HELIODIN",modelo:"HD10 PLUS",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:63.7,eficiencia:52.0,classificacao:"C",area:0.9},
  {marca:"HELIODIN",modelo:"HD10 PLUS T",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:63.7,eficiencia:52.0,classificacao:"C",area:0.9},
  {marca:"HELIODIN",modelo:"HD10 PRIME",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:85.5,eficiencia:62.0,classificacao:"A",area:1.0},
  {marca:"HELIODIN",modelo:"HD10 PRIME INOX",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:71.2,eficiencia:52.2,classificacao:"C",area:1.0},
  {marca:"HELIODIN",modelo:"HD10 PRIME T",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:85.5,eficiencia:62.0,classificacao:"A",area:1.0},
  {marca:"HELIODIN",modelo:"HD10 PRIME T INOX",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:71.2,eficiencia:52.2,classificacao:"C",area:1.0},
  {marca:"HELIODIN",modelo:"HD10 PRO",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:85.5,eficiencia:62.0,classificacao:"A",area:1.0},
  {marca:"HELIODIN",modelo:"HD16 PLUS",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:101.1,eficiencia:52.0,classificacao:"C",area:1.4},
  {marca:"HELIODIN",modelo:"HD16 PLUS T",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:101.1,eficiencia:52.0,classificacao:"C",area:1.4},
  {marca:"HELIODIN",modelo:"HD16 PRIME",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:135.2,eficiencia:62.0,classificacao:"A",area:1.6},
  {marca:"HELIODIN",modelo:"HD16 PRIME INOX",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:113.6,eficiencia:52.2,classificacao:"C",area:1.6},
  {marca:"HELIODIN",modelo:"HD16 PRIME T",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:135.2,eficiencia:62.0,classificacao:"A",area:1.6},
  {marca:"HELIODIN",modelo:"HD16 PRIME T INOX",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:113.6,eficiencia:52.2,classificacao:"C",area:1.6},
  {marca:"HELIODIN",modelo:"HD16 PRO",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:135.2,eficiencia:62.0,classificacao:"A",area:1.6},
  {marca:"HELIODIN",modelo:"HD18 PLUS",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:113.7,eficiencia:52.0,classificacao:"C",area:1.6},
  {marca:"HELIODIN",modelo:"HD18 PLUS T",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:113.7,eficiencia:52.0,classificacao:"C",area:1.6},
  {marca:"HELIODIN",modelo:"HD18 PRIME",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:152.1,eficiencia:62.0,classificacao:"A",area:1.8},
  {marca:"HELIODIN",modelo:"HD18 PRIME INOX",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:127.8,eficiencia:52.2,classificacao:"C",area:1.8},
  {marca:"HELIODIN",modelo:"HD18 PRIME T",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:152.1,eficiencia:62.0,classificacao:"A",area:1.8},
  {marca:"HELIODIN",modelo:"HD18 PRIME T INOX",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:127.8,eficiencia:52.2,classificacao:"C",area:1.8},
  {marca:"HELIODIN",modelo:"HD18 PRO",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:152.1,eficiencia:62.0,classificacao:"A",area:1.8},
  {marca:"HELIODIN",modelo:"HD20 PLUS",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:126.4,eficiencia:52.0,classificacao:"C",area:1.8},
  {marca:"HELIODIN",modelo:"HD20 PLUS T",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:126.4,eficiencia:52.0,classificacao:"C",area:1.8},
  {marca:"HELIODIN",modelo:"HD20 PRIME",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:188.5,eficiencia:68.0,classificacao:"A",area:2.0},
  {marca:"HELIODIN",modelo:"HD20 PRIME INOX",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:165.4,eficiencia:60.1,classificacao:"A",area:2.0},
  {marca:"HELIODIN",modelo:"HD20 PRIME T",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:188.5,eficiencia:68.0,classificacao:"A",area:2.0},
  {marca:"HELIODIN",modelo:"HD20 PRIME T INOX",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:165.4,eficiencia:60.1,classificacao:"A",area:2.0},
  {marca:"HELIODIN",modelo:"HD20 PRO",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:196.2,eficiencia:70.6,classificacao:"A",area:2.0},
  {marca:"HELIODIN",modelo:"HD24 PRO",fornecedor:"RSM Máquinas e Equipamentos Ltda.",producao:233.6,eficiencia:70.6,classificacao:"A",area:2.4},
  {marca:"HELIOTEK",modelo:"ELITE",fornecedor:"Heliotek Termotecnologia Ltda.",producao:202.7,eficiencia:73.1,classificacao:"A",area:2.0},
  {marca:"HELIOTEK",modelo:"ELITEH",fornecedor:"Heliotek Termotecnologia Ltda.",producao:202.7,eficiencia:73.1,classificacao:"A",area:2.0},
  {marca:"HELIOTEK",modelo:"MC1500TF10",fornecedor:"Heliotek Termotecnologia Ltda.",producao:69.2,eficiencia:50.0,classificacao:"C",area:1.0},
  {marca:"HELIOTEK",modelo:"MC1500TF15",fornecedor:"Heliotek Termotecnologia Ltda.",producao:103.5,eficiencia:50.0,classificacao:"C",area:1.5},
  {marca:"HELIOTEK",modelo:"MC1500TF20",fornecedor:"Heliotek Termotecnologia Ltda.",producao:138.0,eficiencia:50.0,classificacao:"C",area:2.0},
  {marca:"HELIOTEK",modelo:"MC3000TF10",fornecedor:"Heliotek Termotecnologia Ltda.",producao:85.7,eficiencia:62.5,classificacao:"A",area:1.0},
  {marca:"HELIOTEK",modelo:"MC3000TF15",fornecedor:"Heliotek Termotecnologia Ltda.",producao:129.1,eficiencia:62.5,classificacao:"A",area:1.5},
  {marca:"HELIOTEK",modelo:"MC3000TF20",fornecedor:"Heliotek Termotecnologia Ltda.",producao:187.9,eficiencia:67.8,classificacao:"A",area:2.0},
  {marca:"HELIOTEK",modelo:"MC3000TF20H",fornecedor:"Heliotek Termotecnologia Ltda.",producao:187.9,eficiencia:67.8,classificacao:"A",area:2.0},
  {marca:"HELIOTEK",modelo:"TOP BLUE 1.0",fornecedor:"Heliotek Termotecnologia Ltda.",producao:87.3,eficiencia:63.0,classificacao:"A",area:1.0},
  {marca:"HELIOTEK",modelo:"TOP BLUE 2.0",fornecedor:"Heliotek Termotecnologia Ltda.",producao:192.0,eficiencia:69.1,classificacao:"A",area:2.0},
  {marca:"HELIOTEK",modelo:"TOP BLUE1.5",fornecedor:"Heliotek Termotecnologia Ltda.",producao:130.6,eficiencia:63.0,classificacao:"A",area:1.5},
  {marca:"HIDRO GOLD",modelo:"COL.HG 2.00 V",fornecedor:"Hidro Gold Aquecedor Solar Eireli",producao:143.6,eficiencia:51.4,classificacao:"C",area:2.0},
  {marca:"INDUSTEK",modelo:"HS10",fornecedor:"Industek",producao:82.4,eficiencia:59.5,classificacao:"A",area:1.0},
  {marca:"INDUSTEK",modelo:"HS15",fornecedor:"Industek",producao:123.0,eficiencia:59.5,classificacao:"A",area:1.5},
  {marca:"INDUSTEK",modelo:"HS20",fornecedor:"Industek",producao:164.0,eficiencia:59.5,classificacao:"A",area:2.0},
  {marca:"JM AQUECEDOR",modelo:"HORIZ. JM 2X1",fornecedor:"J M Aquecedor Solar Eireli",producao:133.2,eficiencia:48.0,classificacao:"C",area:2.0},
  {marca:"JM AQUECEDOR",modelo:"VERT. JM 2X1",fornecedor:"J M Aquecedor Solar Eireli",producao:133.2,eficiencia:48.0,classificacao:"C",area:2.0},
  {marca:"JOULE AQUECEDOR SOLAR",modelo:"Ultra Supreme – US 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:1.0},
  {marca:"JOULE AQUECEDOR SOLAR",modelo:"Ultra Supreme – US 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:1.5},
  {marca:"JOULE AQUECEDOR SOLAR",modelo:"Ultra Supreme – US 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:1.7},
  {marca:"JOULE AQUECEDOR SOLAR",modelo:"Ultra Supreme – US 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:2.0},
  {marca:"KALAHARI",modelo:"Inox Power – IP 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.0},
  {marca:"KALAHARI",modelo:"Inox Power – IP 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.5},
  {marca:"KALAHARI",modelo:"Inox Power – IP 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.7},
  {marca:"KALAHARI",modelo:"Inox Power – IP 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:2.0},
  {marca:"Kisoltec",modelo:"ECO 100",fornecedor:"Kisoltec Aquecedor Solar",producao:67.8,eficiencia:54.0,classificacao:"B",area:0.9},
  {marca:"Kisoltec",modelo:"ECO 150",fornecedor:"Kisoltec Aquecedor Solar",producao:100.8,eficiencia:54.0,classificacao:"B",area:1.4},
  {marca:"Kisoltec",modelo:"ECO 200",fornecedor:"Kisoltec Aquecedor Solar",producao:134.5,eficiencia:54.0,classificacao:"B",area:1.8},
  {marca:"Kisoltec",modelo:"KINOX 100",fornecedor:"Kisoltec Aquecedor Solar",producao:74.3,eficiencia:53.0,classificacao:"B",area:1.0},
  {marca:"Kisoltec",modelo:"KINOX 150",fornecedor:"Kisoltec Aquecedor Solar",producao:111.0,eficiencia:53.0,classificacao:"B",area:1.5},
  {marca:"Kisoltec",modelo:"KINOX 200",fornecedor:"Kisoltec Aquecedor Solar",producao:147.7,eficiencia:53.0,classificacao:"B",area:2.0},
  {marca:"Kisoltec",modelo:"Prime 100",fornecedor:"Kisoltec Aquecedor Solar",producao:81.1,eficiencia:58.0,classificacao:"A",area:1.0},
  {marca:"Kisoltec",modelo:"Prime 150",fornecedor:"Kisoltec Aquecedor Solar",producao:122.0,eficiencia:58.0,classificacao:"A",area:1.5},
  {marca:"Kisoltec",modelo:"Prime 170",fornecedor:"Kisoltec Aquecedor Solar",producao:138.2,eficiencia:58.0,classificacao:"A",area:1.7},
  {marca:"Kisoltec",modelo:"Prime 200",fornecedor:"Kisoltec Aquecedor Solar",producao:162.4,eficiencia:58.0,classificacao:"A",area:2.0},
  {marca:"Kisoltec",modelo:"Prime 200H",fornecedor:"Kisoltec Aquecedor Solar",producao:162.4,eficiencia:58.0,classificacao:"A",area:2.0},
  {marca:"Kisoltec",modelo:"PRIME-TE 150",fornecedor:"Kisoltec Aquecedor Solar",producao:131.7,eficiencia:63.0,classificacao:"A",area:1.5},
  {marca:"Kisoltec",modelo:"PRIME-TE 170",fornecedor:"Kisoltec Aquecedor Solar",producao:150.3,eficiencia:63.0,classificacao:"A",area:1.7},
  {marca:"Kisoltec",modelo:"PRIME-TE 200",fornecedor:"Kisoltec Aquecedor Solar",producao:176.7,eficiencia:63.0,classificacao:"A",area:2.0},
  {marca:"Kisoltec",modelo:"PRIME-TE 200H",fornecedor:"Kisoltec Aquecedor Solar",producao:176.7,eficiencia:63.0,classificacao:"A",area:2.0},
  {marca:"Kisoltec",modelo:"PRIMETEC TE 150",fornecedor:"Kisoltec Aquecedor Solar",producao:122.8,eficiencia:58.0,classificacao:"A",area:1.5},
  {marca:"Kisoltec",modelo:"PRIMETEC TE 170",fornecedor:"Kisoltec Aquecedor Solar",producao:138.4,eficiencia:58.0,classificacao:"A",area:1.7},
  {marca:"Kisoltec",modelo:"PRIMETEC TE 200 HORIZONTAL",fornecedor:"Kisoltec Aquecedor Solar",producao:162.8,eficiencia:58.0,classificacao:"A",area:2.0},
  {marca:"Kisoltec",modelo:"STT 200",fornecedor:"Kisoltec Aquecedor Solar",producao:176.8,eficiencia:88.0,classificacao:"A",area:2.0},
  {marca:"Kisoltec",modelo:"Ultra 100",fornecedor:"Kisoltec Aquecedor Solar",producao:67.7,eficiencia:55.0,classificacao:"B",area:0.9},
  {marca:"Kisoltec",modelo:"Ultra 130",fornecedor:"Kisoltec Aquecedor Solar",producao:87.9,eficiencia:55.0,classificacao:"B",area:1.2},
  {marca:"Kisoltec",modelo:"Ultra 150",fornecedor:"Kisoltec Aquecedor Solar",producao:101.5,eficiencia:55.0,classificacao:"B",area:1.4},
  {marca:"Kisoltec",modelo:"Ultra 170",fornecedor:"Kisoltec Aquecedor Solar",producao:115.0,eficiencia:55.0,classificacao:"B",area:1.5},
  {marca:"Kisoltec",modelo:"Ultra 200",fornecedor:"Kisoltec Aquecedor Solar",producao:135.4,eficiencia:55.0,classificacao:"B",area:1.8},
  {marca:"Kisoltec",modelo:"ULTRA-TE 150",fornecedor:"Kisoltec Aquecedor Solar",producao:111.3,eficiencia:60.0,classificacao:"A",area:1.4},
  {marca:"Kisoltec",modelo:"ULTRA-TE 170",fornecedor:"Kisoltec Aquecedor Solar",producao:126.8,eficiencia:60.0,classificacao:"A",area:1.5},
  {marca:"Kisoltec",modelo:"ULTRA-TE 200",fornecedor:"Kisoltec Aquecedor Solar",producao:149.2,eficiencia:60.0,classificacao:"A",area:1.8},
  {marca:"Kisoltec",modelo:"ULTRATEC TE 150",fornecedor:"Kisoltec Aquecedor Solar",producao:101.7,eficiencia:54.0,classificacao:"B",area:1.4},
  {marca:"Kisoltec",modelo:"ULTRATEC TE 200",fornecedor:"Kisoltec Aquecedor Solar",producao:135.7,eficiencia:54.0,classificacao:"B",area:1.8},
  {marca:"Komeco",modelo:"KOCS AB 1.0",fornecedor:"Komlog Importação Ltda.",producao:77.4,eficiencia:58.9,classificacao:"A",area:1.0},
  {marca:"Komeco",modelo:"KOCS AB 1.5",fornecedor:"Komlog Importação Ltda.",producao:117.7,eficiencia:58.9,classificacao:"A",area:1.5},
  {marca:"Komeco",modelo:"KOCS AB 2.0",fornecedor:"Komlog Importação Ltda.",producao:157.8,eficiencia:58.9,classificacao:"A",area:2.0},
  {marca:"Komeco",modelo:"KOCS AP 1,5M",fornecedor:"Komlog Importação Ltda.",producao:125.4,eficiencia:61.3,classificacao:"A",area:1.5},
  {marca:"Komeco",modelo:"KOCS AP 1.0M",fornecedor:"Komlog Importação Ltda.",producao:78.5,eficiencia:58.7,classificacao:"A",area:1.0},
  {marca:"Komeco",modelo:"KOCS AP 2.0M",fornecedor:"Komlog Importação Ltda.",producao:178.0,eficiencia:65.6,classificacao:"A",area:2.0},
  {marca:"Komeco",modelo:"KOCS MP 1,5M",fornecedor:"Komlog Importação Ltda.",producao:121.4,eficiencia:59.0,classificacao:"A",area:1.5},
  {marca:"Komeco",modelo:"KOCS MP 1M",fornecedor:"Komlog Importação Ltda.",producao:72.3,eficiencia:53.3,classificacao:"B",area:1.0},
  {marca:"Komeco",modelo:"KOCS MP 2M",fornecedor:"Komlog Importação Ltda.",producao:165.2,eficiencia:60.4,classificacao:"A",area:2.0},
  {marca:"Komeco",modelo:"KOCS MX 1.0",fornecedor:"Komlog Importação Ltda.",producao:73.1,eficiencia:55.4,classificacao:"B",area:1.0},
  {marca:"Komeco",modelo:"KOCS MX 1.5",fornecedor:"Komlog Importação Ltda.",producao:111.1,eficiencia:55.4,classificacao:"B",area:1.5},
  {marca:"Komeco",modelo:"KOCS MX 2.0",fornecedor:"Komlog Importação Ltda.",producao:149.2,eficiencia:55.4,classificacao:"B",area:2.0},
  {marca:"Komeco",modelo:"KOCS PP 1,5M",fornecedor:"Komlog Importação Ltda.",producao:133.2,eficiencia:64.8,classificacao:"A",area:1.5},
  {marca:"Komeco",modelo:"KOCS PP 1M",fornecedor:"Komlog Importação Ltda.",producao:81.2,eficiencia:61.3,classificacao:"A",area:1.0},
  {marca:"Komeco",modelo:"KOCS PP 2M",fornecedor:"Komlog Importação Ltda.",producao:196.5,eficiencia:72.1,classificacao:"A",area:2.0},
  {marca:"Komeco",modelo:"KOCS PR 1.5",fornecedor:"Komlog Importação Ltda.",producao:122.6,eficiencia:60.0,classificacao:"A",area:1.4},
  {marca:"Komeco",modelo:"KOCS PR2.0",fornecedor:"Komlog Importação Ltda.",producao:165.2,eficiencia:60.0,classificacao:"A",area:2.0},
  {marca:"Komeco",modelo:"KOCS TV 15AP",fornecedor:"Komlog Importação Ltda.",producao:175.4,eficiencia:81.2,classificacao:"B",area:2.3},
  {marca:"Komeco",modelo:"KOCS TV 15BP 316",fornecedor:"Komlog Importação Ltda.",producao:180.2,eficiencia:88.7,classificacao:"B",area:2.3},
  {marca:"Komeco",modelo:"KOCS TV 20AP",fornecedor:"Komlog Importação Ltda.",producao:232.1,eficiencia:81.2,classificacao:"B",area:3.0},
  {marca:"Komeco",modelo:"KOCS TV 20BP 316",fornecedor:"Komlog Importação Ltda.",producao:232.4,eficiencia:88.7,classificacao:"B",area:3.0},
  {marca:"Komeco",modelo:"KOCS TV 30AP",fornecedor:"Komlog Importação Ltda.",producao:344.6,eficiencia:81.2,classificacao:"B",area:4.5},
  {marca:"Komeco",modelo:"KOCS TV 30BP 316",fornecedor:"Komlog Importação Ltda.",producao:361.3,eficiencia:88.7,classificacao:"B",area:4.7},
  {marca:"LABORATÓRIO DO SOL",modelo:"Ultra Supreme – US 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:102.3,eficiencia:72.6,classificacao:"A",area:1.0},
  {marca:"LABORATÓRIO DO SOL",modelo:"Ultra Supreme – US 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:153.3,eficiencia:72.6,classificacao:"A",area:1.5},
  {marca:"LABORATÓRIO DO SOL",modelo:"Ultra Supreme – US 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:173.8,eficiencia:72.6,classificacao:"A",area:1.7},
  {marca:"LABORATÓRIO DO SOL",modelo:"Ultra Supreme – US 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:204.5,eficiencia:72.6,classificacao:"A",area:2.0},
  {marca:"LARSOL AQUECIMENTO SOLAR",modelo:"15 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:188.8,eficiencia:77.2,classificacao:"A",area:2.3},
  {marca:"LARSOL AQUECIMENTO SOLAR",modelo:"20 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:245.9,eficiencia:77.2,classificacao:"A",area:3.0},
  {marca:"LARSOL AQUECIMENTO SOLAR",modelo:"25 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:307.1,eficiencia:77.2,classificacao:"A",area:3.8},
  {marca:"LARSOL AQUECIMENTO SOLAR",modelo:"30 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:365.1,eficiencia:77.2,classificacao:"A",area:4.5},
  {marca:"LERO FIBRAS",modelo:"Ultra Supreme – US 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:102.3,eficiencia:72.6,classificacao:"A",area:1.0},
  {marca:"LERO FIBRAS",modelo:"Ultra Supreme – US 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:153.3,eficiencia:72.6,classificacao:"A",area:1.5},
  {marca:"LERO FIBRAS",modelo:"Ultra Supreme – US 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:173.8,eficiencia:72.6,classificacao:"A",area:1.7},
  {marca:"LERO FIBRAS",modelo:"Ultra Supreme – US 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:204.5,eficiencia:72.6,classificacao:"A",area:2.0},
  {marca:"MASTERSOL",modelo:"CMS 1030",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:68.6,eficiencia:53.0,classificacao:"B",area:0.9},
  {marca:"MASTERSOL",modelo:"CMS 1300",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:86.2,eficiencia:53.0,classificacao:"B",area:1.2},
  {marca:"MASTERSOL",modelo:"CMS 1570",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:103.9,eficiencia:53.0,classificacao:"B",area:1.4},
  {marca:"MASTERSOL",modelo:"CMS 1830",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:121.6,eficiencia:53.0,classificacao:"B",area:1.7},
  {marca:"MASTERSOL",modelo:"CMS 2000",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:132.7,eficiencia:53.0,classificacao:"B",area:1.8},
  {marca:"MASTERSOL",modelo:"COLETOR SOLAR MASTER CONFORT 1570",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:116.1,eficiencia:59.2,classificacao:"A",area:1.4},
  {marca:"MASTERSOL",modelo:"COLETOR SOLAR MASTER CONFORT 1830",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:136.0,eficiencia:59.2,classificacao:"A",area:1.7},
  {marca:"MASTERSOL",modelo:"COLETOR SOLAR MASTER CONFORT 2000",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:148.3,eficiencia:59.2,classificacao:"A",area:1.8},
  {marca:"MASTERSOL",modelo:"COLETOR SOLAR MASTER INOX 1570",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:106.5,eficiencia:55.5,classificacao:"B",area:1.4},
  {marca:"MASTERSOL",modelo:"COLETOR SOLAR MASTER INOX 1830",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:125.1,eficiencia:55.5,classificacao:"B",area:1.7},
  {marca:"MASTERSOL",modelo:"COLETOR SOLAR MASTER INOX 2000",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:136.4,eficiencia:55.5,classificacao:"B",area:1.8},
  {marca:"MASTERSOL",modelo:"COLETOR SOLAR MASTERTEC 1030",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:67.1,eficiencia:53.4,classificacao:"C",area:1.0},
  {marca:"MASTERSOL",modelo:"COLETOR SOLAR MASTERTEC 1300",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:94.1,eficiencia:53.4,classificacao:"C",area:1.3},
  {marca:"MASTERSOL",modelo:"COLETOR SOLAR MASTERTEC 1530",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:113.7,eficiencia:53.4,classificacao:"C",area:1.4},
  {marca:"MASTERSOL",modelo:"COLETOR SOLAR MASTERTEC 1830",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:132.5,eficiencia:53.4,classificacao:"C",area:1.7},
  {marca:"MASTERSOL",modelo:"COLETOR SOLAR MASTERTEC 2000",fornecedor:"Mastersol Ind. e Com. de Aquecedores Solar Ltda. ME",producao:144.8,eficiencia:53.4,classificacao:"C",area:1.8},
  {marca:"META AQUECEDORES",modelo:"CSMETA15CUVC",fornecedor:"Solar Minas Ltda.",producao:134.3,eficiencia:64.2,classificacao:"A",area:1.5},
  {marca:"META AQUECEDORES",modelo:"CSMETA15CUVSLIM",fornecedor:"Solar Minas Ltda.",producao:103.2,eficiencia:54.7,classificacao:"B",area:1.4},
  {marca:"META AQUECEDORES",modelo:"CSMETA15INVCPLUS",fornecedor:"Solar Minas Ltda.",producao:124.9,eficiencia:58.9,classificacao:"A",area:1.5},
  {marca:"META AQUECEDORES",modelo:"CSMETA20CUVC",fornecedor:"Solar Minas Ltda.",producao:180.2,eficiencia:64.2,classificacao:"A",area:2.0},
  {marca:"META AQUECEDORES",modelo:"CSMETA20CUVSLIM",fornecedor:"Solar Minas Ltda.",producao:137.6,eficiencia:54.7,classificacao:"B",area:1.8},
  {marca:"META AQUECEDORES",modelo:"CSMETA20INVCPLUS",fornecedor:"Solar Minas Ltda.",producao:166.6,eficiencia:58.9,classificacao:"A",area:2.0},
  {marca:"MULTI AQUECIMENTO",modelo:"BP20V",fornecedor:"Aquecedores Max Chama Ltda.",producao:245.9,eficiencia:77.2,classificacao:"A",area:3.0},
  {marca:"MULTI AQUECIMENTO",modelo:"BP25V",fornecedor:"Aquecedores Max Chama Ltda.",producao:307.1,eficiencia:77.2,classificacao:"A",area:3.8},
  {marca:"MULTI AQUECIMENTO",modelo:"BP30H",fornecedor:"Aquecedores Max Chama Ltda.",producao:319.9,eficiencia:58.4,classificacao:"C",area:4.6},
  {marca:"MULTI AQUECIMENTO",modelo:"BP30V",fornecedor:"Aquecedores Max Chama Ltda.",producao:365.1,eficiencia:77.2,classificacao:"A",area:4.5},
  {marca:"MULTI AQUECIMENTO",modelo:"BP40H",fornecedor:"Aquecedores Max Chama Ltda.",producao:414.9,eficiencia:58.4,classificacao:"C",area:5.9},
  {marca:"MULTI AQUECIMENTO",modelo:"BP50H",fornecedor:"Aquecedores Max Chama Ltda.",producao:512.1,eficiencia:58.4,classificacao:"C",area:7.3},
  {marca:"MULTI AQUECIMENTO",modelo:"BP60H",fornecedor:"Aquecedores Max Chama Ltda.",producao:611.9,eficiencia:58.4,classificacao:"C",area:8.8},
  {marca:"NIKSOL",modelo:"CS CB 1,00 x 1,00",fornecedor:"Center Sol Com. e Ind. de Aquecedor Solar",producao:81.8,eficiencia:58.0,classificacao:"A",area:1.0},
  {marca:"NIKSOL",modelo:"CS CB 1,50 x 1,00",fornecedor:"Center Sol Com. e Ind. de Aquecedor Solar",producao:122.5,eficiencia:58.0,classificacao:"A",area:1.5},
  {marca:"NIKSOL",modelo:"CS CB 2,00 x 1,00",fornecedor:"Center Sol Com. e Ind. de Aquecedor Solar",producao:163.3,eficiencia:58.0,classificacao:"A",area:2.0},
  {marca:"Popsol",modelo:"Popsol 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:132.2,eficiencia:61.5,classificacao:"A",area:1.6},
  {marca:"Popsol",modelo:"Popsol 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:148.1,eficiencia:61.5,classificacao:"A",area:1.8},
  {marca:"Popsol",modelo:"Popsol 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:164.5,eficiencia:61.5,classificacao:"A",area:2.0},
  {marca:"Popsol",modelo:"Popsol 2,24 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:184.3,eficiencia:61.5,classificacao:"A",area:2.2},
  {marca:"Popsol",modelo:"Popsol I Inox 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:126.5,eficiencia:59.3,classificacao:"B",area:1.6},
  {marca:"Popsol",modelo:"Popsol I Inox 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:142.1,eficiencia:59.3,classificacao:"B",area:1.8},
  {marca:"Popsol",modelo:"Popsol I Inox 2,07 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:163.4,eficiencia:59.3,classificacao:"B",area:2.1},
  {marca:"Popsol",modelo:"Popsol I Inox 2,24 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:176.8,eficiencia:59.3,classificacao:"B",area:2.2},
  {marca:"Popsol",modelo:"Popsol Mini",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:78.8,eficiencia:60.1,classificacao:"B",area:1.0},
  {marca:"PRO-SOL",modelo:"BLUE 1,72 H LV T",fornecedor:"Pro-Sol Ind. e Com. de Produtos de Energia Solar Ltda.",producao:153.4,eficiencia:65.0,classificacao:"A",area:1.7},
  {marca:"PRO-SOL",modelo:"BLUE 1,72 LV T",fornecedor:"Pro-Sol Ind. e Com. de Produtos de Energia Solar Ltda.",producao:153.4,eficiencia:65.0,classificacao:"A",area:1.7},
  {marca:"PRO-SOL",modelo:"BLUE 1,84 H LV T",fornecedor:"Pro-Sol Ind. e Com. de Produtos de Energia Solar Ltda.",producao:163.9,eficiencia:65.0,classificacao:"A",area:1.8},
  {marca:"PRO-SOL",modelo:"BLUE 1,97 H LV T",fornecedor:"Pro-Sol Ind. e Com. de Produtos de Energia Solar Ltda.",producao:175.5,eficiencia:65.0,classificacao:"A",area:2.0},
  {marca:"PRO-SOL",modelo:"BLUE 2,10 H LV T",fornecedor:"Pro-Sol Ind. e Com. de Produtos de Energia Solar Ltda.",producao:187.1,eficiencia:65.0,classificacao:"A",area:2.1},
  {marca:"PRO-SOL",modelo:"BLUE 8 1,0 LV T",fornecedor:"Pro-Sol Ind. e Com. de Produtos de Energia Solar Ltda.",producao:83.5,eficiencia:59.9,classificacao:"A",area:1.0},
  {marca:"PRO-SOL",modelo:"BLUE 8 1,43 LV T",fornecedor:"Pro-Sol Ind. e Com. de Produtos de Energia Solar Ltda.",producao:119.4,eficiencia:59.9,classificacao:"A",area:1.4},
  {marca:"PRO-SOL",modelo:"BLUE 8 1,78 LV T",fornecedor:"Pro-Sol Ind. e Com. de Produtos de Energia Solar Ltda.",producao:148.6,eficiencia:59.9,classificacao:"A",area:1.8},
  {marca:"PRO-SOL",modelo:"BLUE 8 1,95 LV T",fornecedor:"Pro-Sol Ind. e Com. de Produtos de Energia Solar Ltda.",producao:162.8,eficiencia:59.9,classificacao:"A",area:2.0},
  {marca:"PRO-SOL",modelo:"BLUE 8 2,14 LV T",fornecedor:"Pro-Sol Ind. e Com. de Produtos de Energia Solar Ltda.",producao:178.7,eficiencia:59.9,classificacao:"A",area:2.1},
  {marca:"Prosol",modelo:"ELITE",fornecedor:"Heliotek Termotecnologia Ltda.",producao:202.7,eficiencia:73.1,classificacao:"A",area:2.0},
  {marca:"Prosol",modelo:"ELITEH",fornecedor:"Heliotek Termotecnologia Ltda.",producao:202.7,eficiencia:73.1,classificacao:"A",area:2.0},
  {marca:"Prosol",modelo:"MC1500TF10",fornecedor:"Heliotek Termotecnologia Ltda.",producao:69.2,eficiencia:50.0,classificacao:"C",area:1.0},
  {marca:"Prosol",modelo:"MC1500TF15",fornecedor:"Heliotek Termotecnologia Ltda.",producao:103.5,eficiencia:50.0,classificacao:"C",area:1.5},
  {marca:"Prosol",modelo:"MC1500TF20",fornecedor:"Heliotek Termotecnologia Ltda.",producao:138.0,eficiencia:50.0,classificacao:"C",area:2.0},
  {marca:"Prosol",modelo:"MC3000TF10",fornecedor:"Heliotek Termotecnologia Ltda.",producao:85.7,eficiencia:62.5,classificacao:"A",area:1.0},
  {marca:"Prosol",modelo:"MC3000TF15",fornecedor:"Heliotek Termotecnologia Ltda.",producao:129.1,eficiencia:62.5,classificacao:"A",area:1.5},
  {marca:"Prosol",modelo:"MC3000TF20",fornecedor:"Heliotek Termotecnologia Ltda.",producao:187.9,eficiencia:67.8,classificacao:"A",area:2.0},
  {marca:"Prosol",modelo:"MC3000TF20H",fornecedor:"Heliotek Termotecnologia Ltda.",producao:187.9,eficiencia:67.8,classificacao:"A",area:2.0},
  {marca:"Prosol",modelo:"TOP BLUE 1.0",fornecedor:"Heliotek Termotecnologia Ltda.",producao:87.3,eficiencia:63.0,classificacao:"A",area:1.0},
  {marca:"Prosol",modelo:"TOP BLUE 2.0",fornecedor:"Heliotek Termotecnologia Ltda.",producao:192.0,eficiencia:69.1,classificacao:"A",area:2.0},
  {marca:"Prosol",modelo:"TOP BLUE1.5",fornecedor:"Heliotek Termotecnologia Ltda.",producao:130.6,eficiencia:63.0,classificacao:"A",area:1.5},
  {marca:"REAFRIO",modelo:"Ultra Supreme – US 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:102.3,eficiencia:72.6,classificacao:"A",area:1.0},
  {marca:"REAFRIO",modelo:"Ultra Supreme – US 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:153.3,eficiencia:72.6,classificacao:"A",area:1.5},
  {marca:"REAFRIO",modelo:"Ultra Supreme – US 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:173.8,eficiencia:72.6,classificacao:"A",area:1.7},
  {marca:"REAFRIO",modelo:"Ultra Supreme – US 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:204.5,eficiencia:72.6,classificacao:"A",area:2.0},
  {marca:"Ribsol Energia Solar",modelo:"Linha Eco 100x90cm aço inox",fornecedor:"E. S. Dallalana",producao:128.1,eficiencia:51.9,classificacao:"C",area:1.8},
  {marca:"Ribsol Energia Solar",modelo:"Linha Eco 150x90cm aço inox",fornecedor:"E. S. Dallalana",producao:96.1,eficiencia:51.9,classificacao:"C",area:1.4},
  {marca:"Ribsol Energia Solar",modelo:"Linha Eco 200x90cm aço inox",fornecedor:"E. S. Dallalana",producao:64.0,eficiencia:51.9,classificacao:"C",area:0.9},
  {marca:"RINNAI",modelo:"RSC-1000T",fornecedor:"Rinnai Brasil Tecnologia de Aquecimento Ltda.",producao:83.1,eficiencia:61.6,classificacao:"A",area:1.0},
  {marca:"RINNAI",modelo:"RSC-1002V",fornecedor:"Rinnai Brasil Tecnologia de Aquecimento Ltda.",producao:70.7,eficiencia:52.5,classificacao:"C",area:1.0},
  {marca:"RINNAI",modelo:"RSC-1400T",fornecedor:"Rinnai Brasil Tecnologia de Aquecimento Ltda.",producao:115.8,eficiencia:61.6,classificacao:"A",area:1.4},
  {marca:"RINNAI",modelo:"RSC-1402V",fornecedor:"Rinnai Brasil Tecnologia de Aquecimento Ltda.",producao:98.3,eficiencia:52.5,classificacao:"C",area:1.4},
  {marca:"RINNAI",modelo:"RSC-2000T",fornecedor:"Rinnai Brasil Tecnologia de Aquecimento Ltda.",producao:165.3,eficiencia:61.6,classificacao:"A",area:2.0},
  {marca:"RINNAI",modelo:"RSC-2002V",fornecedor:"Rinnai Brasil Tecnologia de Aquecimento Ltda.",producao:140.9,eficiencia:52.5,classificacao:"C",area:2.0},
  {marca:"RINNAI",modelo:"RSC1000BFV",fornecedor:"Rinnai Brasil Tecnologia de Aquecimento Ltda.",producao:72.7,eficiencia:52.5,classificacao:"C",area:1.0},
  {marca:"RINNAI",modelo:"RSC1000TFV",fornecedor:"Rinnai Brasil Tecnologia de Aquecimento Ltda.",producao:85.9,eficiencia:62.5,classificacao:"A",area:1.0},
  {marca:"RINNAI",modelo:"RSC1400BFV",fornecedor:"Rinnai Brasil Tecnologia de Aquecimento Ltda.",producao:101.3,eficiencia:52.5,classificacao:"C",area:1.4},
  {marca:"RINNAI",modelo:"RSC1400TFV",fornecedor:"Rinnai Brasil Tecnologia de Aquecimento Ltda.",producao:119.7,eficiencia:62.5,classificacao:"A",area:1.4},
  {marca:"RINNAI",modelo:"RSC2000BFV",fornecedor:"Rinnai Brasil Tecnologia de Aquecimento Ltda.",producao:144.6,eficiencia:52.5,classificacao:"C",area:2.0},
  {marca:"RINNAI",modelo:"RSC2000TFV",fornecedor:"Rinnai Brasil Tecnologia de Aquecimento Ltda.",producao:194.4,eficiencia:69.8,classificacao:"A",area:2.0},
  {marca:"RIOSOL",modelo:"CS 150",fornecedor:"Indústria e Com. de Aquecedores Solar Brocanelli Ltda. ME",producao:99.2,eficiencia:52.8,classificacao:"C",area:1.4},
  {marca:"RIOSOL",modelo:"CS 200",fornecedor:"Indústria e Com. de Aquecedores Solar Brocanelli Ltda. ME",producao:132.0,eficiencia:52.8,classificacao:"C",area:1.9},
  {marca:"RIOSOL",modelo:"RS 1500",fornecedor:"Indústria e Comércio de Aquecedores Solar Riosol",producao:107.2,eficiencia:57.3,classificacao:"B",area:1.4},
  {marca:"RIOSOL",modelo:"RS 2000",fornecedor:"Indústria e Comércio de Aquecedores Solar Riosol",producao:143.5,eficiencia:57.3,classificacao:"B",area:1.8},
  {marca:"RIOSOL",modelo:"YESHUA 1.5",fornecedor:"Indústria e Comércio de Aquecedores Solar Riosol",producao:112.2,eficiencia:59.7,classificacao:"A",area:1.4},
  {marca:"RIOSOL",modelo:"YESHUA 2.0",fornecedor:"Indústria e Comércio de Aquecedores Solar Riosol",producao:150.3,eficiencia:59.7,classificacao:"A",area:1.9},
  {marca:"SOLAR GLOBAL",modelo:"COLETOR SOLAR DE 15 TUBOS BP",fornecedor:"Solar Global Brasil Distribuição Ltda.",producao:185.1,eficiencia:71.1,classificacao:"A",area:2.3},
  {marca:"SOLAR GLOBAL",modelo:"COLETOR SOLAR DE 20 TUBOS BP",fornecedor:"Solar Global Brasil Distribuição Ltda.",producao:240.2,eficiencia:71.1,classificacao:"A",area:3.0},
  {marca:"SOLAR GLOBAL",modelo:"COLETOR SOLAR DE 25 TUBOS BP",fornecedor:"Solar Global Brasil Distribuição Ltda.",producao:297.3,eficiencia:71.1,classificacao:"A",area:3.7},
  {marca:"SOLAR GLOBAL",modelo:"COLETOR SOLAR DE 30 TUBOS BP",fornecedor:"Solar Global Brasil Distribuição Ltda.",producao:354.9,eficiencia:71.1,classificacao:"A",area:4.4},
  {marca:"SOLAR GLOBAL",modelo:"CS CB 1,00 x 1,00",fornecedor:"Center Sol Com. e Ind. de Aquecedor Solar",producao:81.8,eficiencia:58.0,classificacao:"A",area:1.0},
  {marca:"SOLAR GLOBAL",modelo:"CS CB 1,50 x 1,00",fornecedor:"Center Sol Com. e Ind. de Aquecedor Solar",producao:122.5,eficiencia:58.0,classificacao:"A",area:1.5},
  {marca:"SOLAR GLOBAL",modelo:"CS CB 2,00 x 1,00",fornecedor:"Center Sol Com. e Ind. de Aquecedor Solar",producao:163.3,eficiencia:58.0,classificacao:"A",area:2.0},
  {marca:"SOLAR MINAS",modelo:"SM15i",fornecedor:"Solar Minas Ltda.",producao:134.3,eficiencia:64.2,classificacao:"A",area:1.5},
  {marca:"SOLAR MINAS",modelo:"SM15Plus",fornecedor:"Solar Minas Ltda.",producao:124.9,eficiencia:58.9,classificacao:"A",area:1.5},
  {marca:"SOLAR MINAS",modelo:"SM15Slim",fornecedor:"Solar Minas Ltda.",producao:103.2,eficiencia:54.7,classificacao:"B",area:1.4},
  {marca:"SOLAR MINAS",modelo:"SM18i",fornecedor:"Solar Minas Ltda.",producao:161.9,eficiencia:64.2,classificacao:"A",area:1.8},
  {marca:"SOLAR MINAS",modelo:"SM18Plus",fornecedor:"Solar Minas Ltda.",producao:151.4,eficiencia:58.9,classificacao:"A",area:1.8},
  {marca:"SOLAR MINAS",modelo:"SM18Slim",fornecedor:"Solar Minas Ltda.",producao:123.9,eficiencia:54.7,classificacao:"B",area:1.6},
  {marca:"SOLAR MINAS",modelo:"SM20i",fornecedor:"Solar Minas Ltda.",producao:180.2,eficiencia:64.2,classificacao:"A",area:2.0},
  {marca:"SOLAR MINAS",modelo:"SM20Plus",fornecedor:"Solar Minas Ltda.",producao:166.6,eficiencia:58.9,classificacao:"A",area:2.0},
  {marca:"SOLAR MINAS",modelo:"SM20Slim",fornecedor:"Solar Minas Ltda.",producao:137.6,eficiencia:54.7,classificacao:"B",area:1.8},
  {marca:"SOLAR SILVA",modelo:"Inox Power – IP 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.0},
  {marca:"SOLAR SILVA",modelo:"Inox Power – IP 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.5},
  {marca:"SOLAR SILVA",modelo:"Inox Power – IP 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.7},
  {marca:"SOLAR SILVA",modelo:"Inox Power – IP 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:2.0},
  {marca:"SOLAR SILVA",modelo:"Ultra Supreme – US 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:102.3,eficiencia:72.6,classificacao:"A",area:1.0},
  {marca:"SOLAR SILVA",modelo:"Ultra Supreme – US 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:153.3,eficiencia:72.6,classificacao:"A",area:1.5},
  {marca:"SOLAR SILVA",modelo:"Ultra Supreme – US 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:173.8,eficiencia:72.6,classificacao:"A",area:1.7},
  {marca:"SOLAR SILVA",modelo:"Ultra Supreme – US 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:204.5,eficiencia:72.6,classificacao:"A",area:2.0},
  {marca:"SOLAR VAC",modelo:"15 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:188.8,eficiencia:77.2,classificacao:"A",area:2.3},
  {marca:"SOLAR VAC",modelo:"20 TUBOS AP",fornecedor:"Aquecedores Max Chama Ltda.",producao:247.5,eficiencia:75.3,classificacao:"A",area:3.0},
  {marca:"SOLAR VAC",modelo:"20 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:245.9,eficiencia:77.2,classificacao:"A",area:3.0},
  {marca:"SOLAR VAC",modelo:"25 TUBOS AP",fornecedor:"Aquecedores Max Chama Ltda.",producao:304.2,eficiencia:75.3,classificacao:"A",area:3.7},
  {marca:"SOLAR VAC",modelo:"25 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:307.1,eficiencia:77.2,classificacao:"A",area:3.8},
  {marca:"SOLAR VAC",modelo:"30 TUBOS AP",fornecedor:"Aquecedores Max Chama Ltda.",producao:362.3,eficiencia:75.3,classificacao:"A",area:4.4},
  {marca:"SOLAR VAC",modelo:"30 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:365.1,eficiencia:77.2,classificacao:"A",area:4.5},
  {marca:"SOLAR VAC",modelo:"30 TUBOS BP HORIZONTAL",fornecedor:"Aquecedores Max Chama Ltda.",producao:319.9,eficiencia:58.4,classificacao:"C",area:4.6},
  {marca:"SOLAR VAC",modelo:"40 TUBOS BP HORIZONTAL",fornecedor:"Aquecedores Max Chama Ltda.",producao:414.9,eficiencia:58.4,classificacao:"C",area:5.9},
  {marca:"SOLAR VAC",modelo:"50 TUBOS BP HORIZONTAL",fornecedor:"Aquecedores Max Chama Ltda.",producao:512.1,eficiencia:58.4,classificacao:"C",area:7.3},
  {marca:"SOLAR VAC",modelo:"60 TUBOS BP HORIZONTAL",fornecedor:"Aquecedores Max Chama Ltda.",producao:611.9,eficiencia:58.4,classificacao:"C",area:8.8},
  {marca:"SOLAREM",modelo:"Equinox 160",fornecedor:"Tuma Industrial Ltda.",producao:129.7,eficiencia:58.0,classificacao:"A",area:1.6},
  {marca:"SOLAREM",modelo:"Equinox 180",fornecedor:"Tuma Industrial Ltda.",producao:145.7,eficiencia:58.0,classificacao:"A",area:1.8},
  {marca:"SOLAREM",modelo:"Equinox 200",fornecedor:"Tuma Industrial Ltda.",producao:161.8,eficiencia:58.0,classificacao:"A",area:2.0},
  {marca:"SOLAREM",modelo:"Lira 100",fornecedor:"Tuma Industrial Ltda.",producao:95.7,eficiencia:69.5,classificacao:"A",area:1.0},
  {marca:"SOLAREM",modelo:"Lira 130",fornecedor:"Tuma Industrial Ltda.",producao:124.3,eficiencia:69.5,classificacao:"A",area:1.3},
  {marca:"SOLAREM",modelo:"Lira 160",fornecedor:"Tuma Industrial Ltda.",producao:154.1,eficiencia:69.5,classificacao:"A",area:1.6},
  {marca:"SOLAREM",modelo:"Lira 180",fornecedor:"Tuma Industrial Ltda.",producao:172.1,eficiencia:69.5,classificacao:"A",area:1.8},
  {marca:"SOLAREM",modelo:"Lira 200",fornecedor:"Tuma Industrial Ltda.",producao:191.2,eficiencia:69.5,classificacao:"A",area:2.0},
  {marca:"SOLAREM",modelo:"Pégaso Plus 100",fornecedor:"Tuma Industrial Ltda.",producao:93.5,eficiencia:66.8,classificacao:"A",area:1.0},
  {marca:"SOLAREM",modelo:"Pégaso Plus 130",fornecedor:"Tuma Industrial Ltda.",producao:121.3,eficiencia:66.8,classificacao:"A",area:1.3},
  {marca:"SOLAREM",modelo:"Pégaso Plus 170",fornecedor:"Tuma Industrial Ltda.",producao:158.5,eficiencia:66.8,classificacao:"A",area:1.7},
  {marca:"SOLAREM",modelo:"Pégaso Plus 180",fornecedor:"Tuma Industrial Ltda.",producao:167.8,eficiencia:66.8,classificacao:"A",area:1.8},
  {marca:"SOLAREM",modelo:"Pégaso Plus 200",fornecedor:"Tuma Industrial Ltda.",producao:186.4,eficiencia:66.8,classificacao:"A",area:2.0},
  {marca:"Solarium",modelo:"PP-150-B",fornecedor:"Heliosol Indústria e Comércio de Aquecedores Solar Ltda.",producao:178.3,eficiencia:72.5,classificacao:"A",area:1.7},
  {marca:"Solarium",modelo:"PP-200-B",fornecedor:"Heliosol Indústria e Comércio de Aquecedores Solar Ltda.",producao:245.9,eficiencia:72.5,classificacao:"A",area:2.3},
  {marca:"Solarium",modelo:"PP-300-B",fornecedor:"Heliosol Indústria e Comércio de Aquecedores Solar Ltda.",producao:374.6,eficiencia:72.5,classificacao:"A",area:3.6},
  {marca:"Solarium",modelo:"PP-400-B",fornecedor:"Heliosol Indústria e Comércio de Aquecedores Solar Ltda.",producao:499.5,eficiencia:72.5,classificacao:"A",area:4.8},
  {marca:"Solarium",modelo:"PP-500-B",fornecedor:"Heliosol Indústria e Comércio de Aquecedores Solar Ltda.",producao:624.4,eficiencia:72.5,classificacao:"A",area:6.0},
  {marca:"Solarmax",modelo:"Solarmax 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:132.2,eficiencia:61.5,classificacao:"A",area:1.6},
  {marca:"Solarmax",modelo:"Solarmax 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:148.1,eficiencia:61.5,classificacao:"A",area:1.8},
  {marca:"Solarmax",modelo:"Solarmax 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:164.5,eficiencia:61.5,classificacao:"A",area:2.0},
  {marca:"Solarmax",modelo:"Solarmax 2,24 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:184.3,eficiencia:61.5,classificacao:"A",area:2.2},
  {marca:"Solarmax",modelo:"Solarmax Calha 15 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:132.2,eficiencia:61.5,classificacao:"A",area:1.6},
  {marca:"Solarmax",modelo:"Solarmax Calha 15 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:164.5,eficiencia:61.5,classificacao:"A",area:2.0},
  {marca:"Solarmax",modelo:"Solarmax I Calha 15 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:126.5,eficiencia:59.3,classificacao:"B",area:1.6},
  {marca:"Solarmax",modelo:"Solarmax I Calha 15 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:142.1,eficiencia:59.3,classificacao:"B",area:1.8},
  {marca:"Solarmax",modelo:"Solarmax I Calha 15 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:157.8,eficiencia:59.3,classificacao:"B",area:2.0},
  {marca:"Solarmax",modelo:"Solarmax I Inox 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:126.5,eficiencia:59.3,classificacao:"B",area:1.6},
  {marca:"Solarmax",modelo:"Solarmax I Inox 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:142.1,eficiencia:59.3,classificacao:"B",area:1.8},
  {marca:"Solarmax",modelo:"Solarmax I Inox 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:157.8,eficiencia:59.3,classificacao:"B",area:2.0},
  {marca:"Solarmax",modelo:"Solarmax I Inox 2,07 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:163.4,eficiencia:59.3,classificacao:"B",area:2.1},
  {marca:"Solarmax",modelo:"Solarmax I Inox 2,24 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:176.8,eficiencia:59.3,classificacao:"B",area:2.2},
  {marca:"Solarmax",modelo:"Solarmax IC 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:134.1,eficiencia:62.9,classificacao:"A",area:1.6},
  {marca:"Solarmax",modelo:"Solarmax IC 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:150.5,eficiencia:62.9,classificacao:"A",area:1.8},
  {marca:"Solarmax",modelo:"Solarmax IC 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:167.2,eficiencia:62.9,classificacao:"A",area:2.0},
  {marca:"Solarmax",modelo:"Solarmax IC 2,24 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:187.3,eficiencia:62.9,classificacao:"A",area:2.2},
  {marca:"Solarmax",modelo:"Solarmax II 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:123.9,eficiencia:58.0,classificacao:"B",area:1.6},
  {marca:"Solarmax",modelo:"Solarmax II 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:139.1,eficiencia:58.0,classificacao:"B",area:1.8},
  {marca:"Solarmax",modelo:"Solarmax II 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:154.6,eficiencia:58.0,classificacao:"B",area:2.0},
  {marca:"Solarmax",modelo:"Solarmax Mini",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:78.8,eficiencia:60.1,classificacao:"B",area:1.0},
  {marca:"SOLATIVO",modelo:"Ultra Supreme – US 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:1.0},
  {marca:"SOLATIVO",modelo:"Ultra Supreme – US 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:1.5},
  {marca:"SOLATIVO",modelo:"Ultra Supreme – US 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:1.7},
  {marca:"SOLATIVO",modelo:"Ultra Supreme – US 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:81.5,eficiencia:59.4,classificacao:"A",area:2.0},
  {marca:"Soletrol",modelo:"Max Alumínio 1,5 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:118.2,eficiencia:60.1,classificacao:"B",area:1.5},
  {marca:"Soletrol",modelo:"Max Alumínio Cobre 1,6 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:132.2,eficiencia:61.5,classificacao:"A",area:1.6},
  {marca:"Soletrol",modelo:"Max Alumínio Cobre 1,60 m² Horizontal",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:132.2,eficiencia:61.5,classificacao:"A",area:1.6},
  {marca:"Soletrol",modelo:"Max Alumínio Cobre 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:148.1,eficiencia:61.5,classificacao:"A",area:1.8},
  {marca:"Soletrol",modelo:"Max Alumínio Cobre 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:164.5,eficiencia:61.5,classificacao:"A",area:2.0},
  {marca:"Soletrol",modelo:"Max Alumínio Cobre 2,24 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:184.3,eficiencia:61.5,classificacao:"A",area:2.2},
  {marca:"Soletrol",modelo:"Max Alumínio Inox 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:126.5,eficiencia:59.3,classificacao:"B",area:1.6},
  {marca:"Soletrol",modelo:"Max Alumínio Inox 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:142.1,eficiencia:59.3,classificacao:"B",area:1.8},
  {marca:"Soletrol",modelo:"Max Alumínio Inox 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:157.8,eficiencia:59.3,classificacao:"B",area:2.0},
  {marca:"Soletrol",modelo:"Max Alumínio Inox 2,24 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:176.8,eficiencia:59.3,classificacao:"B",area:2.2},
  {marca:"Soletrol",modelo:"Max Inox 1,5 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:111.7,eficiencia:56.5,classificacao:"B",area:1.5},
  {marca:"Soletrol",modelo:"Mini Max Alumínio 1,0 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:78.8,eficiencia:60.1,classificacao:"B",area:1.0},
  {marca:"Soletrol",modelo:"Mini Max Inox 1,0 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:74.4,eficiencia:56.5,classificacao:"B",area:1.0},
  {marca:"Soletrol",modelo:"Soletrol Max Inox Cobre 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:134.1,eficiencia:62.9,classificacao:"A",area:1.6},
  {marca:"Soletrol",modelo:"Soletrol Max Inox Cobre 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:150.5,eficiencia:62.9,classificacao:"A",area:1.8},
  {marca:"Soletrol",modelo:"Soletrol Max Inox Cobre 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:167.2,eficiencia:62.9,classificacao:"A",area:2.0},
  {marca:"Soletrol",modelo:"Soletrol Max Inox Cobre 2,24 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:187.3,eficiencia:62.9,classificacao:"A",area:2.2},
  {marca:"Soletrol",modelo:"Soletrol Max Inox Inox 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:123.9,eficiencia:58.0,classificacao:"B",area:1.6},
  {marca:"Soletrol",modelo:"Soletrol Max Inox Inox 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:139.1,eficiencia:58.0,classificacao:"B",area:1.8},
  {marca:"Soletrol",modelo:"Soletrol Max Inox Inox 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:154.6,eficiencia:58.0,classificacao:"B",area:2.0},
  {marca:"Solis Solar",modelo:"ECO V150",fornecedor:"Solis Ind. e Com. de Aquecedor Solar S/A.",producao:104.4,eficiencia:50.6,classificacao:"C",area:1.5},
  {marca:"Solis Solar",modelo:"ECO V200",fornecedor:"Solis Ind. e Com. de Aquecedor Solar S/A.",producao:137.2,eficiencia:50.6,classificacao:"C",area:2.0},
  {marca:"Solis Solar",modelo:"TROPICOS V150",fornecedor:"Solis Ind. e Com. de Aquecedor Solar S/A.",producao:130.2,eficiencia:62.8,classificacao:"A",area:1.5},
  {marca:"Solis Solar",modelo:"TRÓPICOS ALFA V 100",fornecedor:"Solis Ind. e Com. de Aquecedor Solar S/A.",producao:73.2,eficiencia:53.9,classificacao:"C",area:1.0},
  {marca:"Solis Solar",modelo:"TRÓPICOS INOX V 100",fornecedor:"Solis Ind. e Com. de Aquecedor Solar S/A.",producao:72.1,eficiencia:52.4,classificacao:"C",area:1.0},
  {marca:"Solis Solar",modelo:"TRÓPICOS INOX V 150",fornecedor:"Solis Ind. e Com. de Aquecedor Solar S/A.",producao:116.9,eficiencia:58.0,classificacao:"B",area:1.5},
  {marca:"Solis Solar",modelo:"TRÓPICOS INOX V 200",fornecedor:"Solis Ind. e Com. de Aquecedor Solar S/A.",producao:155.7,eficiencia:60.0,classificacao:"A",area:2.0},
  {marca:"Solis Solar",modelo:"TRÓPICOS OMEGA H200",fornecedor:"Solis Ind. e Com. de Aquecedor Solar S/A.",producao:182.2,eficiencia:65.2,classificacao:"A",area:2.0},
  {marca:"Solis Solar",modelo:"TRÓPICOS OMEGA V200",fornecedor:"Solis Ind. e Com. de Aquecedor Solar S/A.",producao:182.2,eficiencia:65.2,classificacao:"A",area:2.0},
  {marca:"Solquent",modelo:"Solquent 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:132.2,eficiencia:61.5,classificacao:"A",area:1.6},
  {marca:"Solquent",modelo:"Solquent 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:148.1,eficiencia:61.5,classificacao:"A",area:1.8},
  {marca:"Solquent",modelo:"Solquent 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:164.5,eficiencia:61.5,classificacao:"A",area:2.0},
  {marca:"Solquent",modelo:"Solquent 2,24 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:184.3,eficiencia:61.5,classificacao:"A",area:2.2},
  {marca:"Solquent",modelo:"Solquent I Calha 15 Inox 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:126.5,eficiencia:59.3,classificacao:"B",area:1.6},
  {marca:"Solquent",modelo:"Solquent I Calha 15 Inox 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:142.1,eficiencia:59.3,classificacao:"B",area:1.8},
  {marca:"Solquent",modelo:"Solquent I Calha 15 Inox 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:157.8,eficiencia:59.3,classificacao:"B",area:2.0},
  {marca:"Solquent",modelo:"Solquent I Inox 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:126.5,eficiencia:59.3,classificacao:"B",area:1.6},
  {marca:"Solquent",modelo:"Solquent I Inox 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:142.1,eficiencia:59.3,classificacao:"B",area:1.8},
  {marca:"Solquent",modelo:"Solquent I Inox 2,07 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:163.4,eficiencia:59.3,classificacao:"B",area:2.1},
  {marca:"Solquent",modelo:"Solquent I Inox 2,26 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:178.4,eficiencia:59.3,classificacao:"B",area:2.3},
  {marca:"Solquent",modelo:"Solquent IC 1,60 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:134.1,eficiencia:62.9,classificacao:"A",area:1.6},
  {marca:"Solquent",modelo:"Solquent IC 1,80 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:150.5,eficiencia:62.9,classificacao:"A",area:1.8},
  {marca:"Solquent",modelo:"Solquent IC 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:167.2,eficiencia:62.9,classificacao:"A",area:2.0},
  {marca:"Solquent",modelo:"Solquent IC 2,24 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:187.3,eficiencia:62.9,classificacao:"A",area:2.2},
  {marca:"Soria",modelo:"Banhos H2.0",fornecedor:"Soria Aquecedor Solar Eireli - EPP",producao:153.7,eficiencia:55.1,classificacao:"B",area:2.0},
  {marca:"Soria",modelo:"Banhos H2.0 VT",fornecedor:"Soria Aquecedor Solar Eireli - EPP",producao:153.7,eficiencia:55.1,classificacao:"B",area:2.0},
  {marca:"Soria",modelo:"Banhos Inox H2.0",fornecedor:"Soria Aquecedor Solar Eireli - EPP",producao:141.2,eficiencia:50.6,classificacao:"C",area:2.0},
  {marca:"Soria",modelo:"Banhos Inox H2.0 VT",fornecedor:"Soria Aquecedor Solar Eireli - EPP",producao:141.2,eficiencia:50.6,classificacao:"C",area:2.0},
  {marca:"Soria",modelo:"Banhos Inox V1.5",fornecedor:"Soria Aquecedor Solar Eireli - EPP",producao:105.9,eficiencia:50.6,classificacao:"C",area:1.5},
  {marca:"Soria",modelo:"Banhos Inox V1.5 VT",fornecedor:"Soria Aquecedor Solar Eireli - EPP",producao:105.9,eficiencia:50.6,classificacao:"C",area:1.5},
  {marca:"Soria",modelo:"Banhos Inox V2.0",fornecedor:"Soria Aquecedor Solar Eireli - EPP",producao:141.2,eficiencia:50.6,classificacao:"C",area:2.0},
  {marca:"Soria",modelo:"Banhos Inox V2.0 VT",fornecedor:"Soria Aquecedor Solar Eireli - EPP",producao:141.2,eficiencia:50.6,classificacao:"C",area:2.0},
  {marca:"Soria",modelo:"Banhos V1.5",fornecedor:"Soria Aquecedor Solar Eireli - EPP",producao:115.3,eficiencia:55.1,classificacao:"B",area:1.5},
  {marca:"Soria",modelo:"Banhos V1.5 VT",fornecedor:"Soria Aquecedor Solar Eireli - EPP",producao:115.3,eficiencia:55.1,classificacao:"B",area:1.5},
  {marca:"Soria",modelo:"Banhos V2.0",fornecedor:"Soria Aquecedor Solar Eireli - EPP",producao:153.7,eficiencia:55.1,classificacao:"B",area:2.0},
  {marca:"Soria",modelo:"Banhos V2.0 VT",fornecedor:"Soria Aquecedor Solar Eireli - EPP",producao:153.7,eficiencia:55.1,classificacao:"B",area:2.0},
  {marca:"SUNPOP",modelo:"CSP-1-15",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:176.0,eficiencia:72.4,classificacao:"B",area:2.3},
  {marca:"SUNPOP",modelo:"CSP-1-20",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:228.9,eficiencia:72.4,classificacao:"B",area:3.0},
  {marca:"SUNPOP",modelo:"CSP-1-25",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:284.3,eficiencia:72.4,classificacao:"B",area:3.7},
  {marca:"SUNPOP",modelo:"CSP-1-30",fornecedor:"Ecologic Distribuidora e Importadora Ltda.",producao:338.3,eficiencia:72.4,classificacao:"B",area:4.5},
  {marca:"TECNOTERMI",modelo:"TTC 1,00 x 1,00",fornecedor:"Assenco Aquecedores e Sistemas Eireli",producao:69.4,eficiencia:50.3,classificacao:"C",area:1.0},
  {marca:"TECNOTERMI",modelo:"TTC 1,40 x 1,00",fornecedor:"Assenco Aquecedores e Sistemas Eireli",producao:97.2,eficiencia:50.3,classificacao:"C",area:1.4},
  {marca:"TECNOTERMI",modelo:"TTC 1,50 x 1,00",fornecedor:"Assenco Aquecedores e Sistemas Eireli",producao:104.1,eficiencia:50.3,classificacao:"C",area:1.5},
  {marca:"TECNOTERMI",modelo:"TTC 1,70 x 1,00",fornecedor:"Assenco Aquecedores e Sistemas Eireli",producao:118.0,eficiencia:50.3,classificacao:"C",area:1.7},
  {marca:"TECNOTERMI",modelo:"TTC 2,00 x 1,00",fornecedor:"Assenco Aquecedores e Sistemas Eireli",producao:138.8,eficiencia:50.3,classificacao:"C",area:2.0},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Inox Soft 1,00X1,00",fornecedor:"Temper-Sol Indústria e Comércio de Aquecedores Ltda.",producao:73.6,eficiencia:53.5,classificacao:"B",area:1.0},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Inox Soft 1,50X1,00",fornecedor:"Temper-Sol Indústria e Comércio de Aquecedores Ltda.",producao:110.5,eficiencia:53.5,classificacao:"B",area:1.5},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Inox Soft 1,70X1,00",fornecedor:"Temper-Sol Indústria e Comércio de Aquecedores Ltda.",producao:125.2,eficiencia:53.5,classificacao:"B",area:1.7},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Inox Soft 2,00X1,00",fornecedor:"Temper-Sol Indústria e Comércio de Aquecedores Ltda.",producao:147.3,eficiencia:53.5,classificacao:"B",area:2.0},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Premium 1,00X1,00",fornecedor:"Temper-Sol Indústria e Comércio de Aquecedores Ltda.",producao:80.8,eficiencia:58.5,classificacao:"A",area:1.0},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Premium 1,50X1,00",fornecedor:"Temper-Sol Indústria e Comércio de Aquecedores Ltda.",producao:120.7,eficiencia:58.5,classificacao:"A",area:1.5},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Premium 1,70X1,00",fornecedor:"Temper-Sol Indústria e Comércio de Aquecedores Ltda.",producao:136.7,eficiencia:58.5,classificacao:"A",area:1.7},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Premium 2,00X1,00",fornecedor:"Temper-Sol Indústria e Comércio de Aquecedores Ltda.",producao:160.9,eficiencia:58.5,classificacao:"A",area:2.0},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Soft 1,00 x 1,00",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:71.7,eficiencia:51.7,classificacao:"C",area:1.0},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Soft 1,00X1,00",fornecedor:"Temper-Sol Indústria e Comércio de Aquecedores Ltda.",producao:70.6,eficiencia:51.2,classificacao:"C",area:1.0},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Soft 1,50 x 1,00",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:107.0,eficiencia:51.7,classificacao:"C",area:1.5},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Soft 1,50X1,00",fornecedor:"Temper-Sol Indústria e Comércio de Aquecedores Ltda.",producao:105.6,eficiencia:51.2,classificacao:"C",area:1.5},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Soft 1,70 x 1,00",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:120.5,eficiencia:51.7,classificacao:"C",area:1.7},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Soft 1,70X1,00",fornecedor:"Temper-Sol Indústria e Comércio de Aquecedores Ltda.",producao:119.7,eficiencia:51.2,classificacao:"C",area:1.7},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Soft 2,00 x 1,00",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:141.7,eficiencia:51.7,classificacao:"C",area:2.0},
  {marca:"TEMPERSOL",modelo:"Coletor Solar Vertical Soft 2,00X1,00",fornecedor:"Temper-Sol Indústria e Comércio de Aquecedores Ltda.",producao:140.8,eficiencia:51.2,classificacao:"C",area:2.0},
  {marca:"TERMOMAX",modelo:"Inox Efficiency - IE 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:92.6,eficiencia:65.8,classificacao:"A",area:1.0},
  {marca:"TERMOMAX",modelo:"Inox Efficiency - IE 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:138.9,eficiencia:65.8,classificacao:"A",area:1.5},
  {marca:"TERMOMAX",modelo:"Inox Efficiency - IE 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:157.4,eficiencia:65.8,classificacao:"A",area:1.7},
  {marca:"TERMOMAX",modelo:"Inox Efficiency - IE 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:185.1,eficiencia:65.8,classificacao:"A",area:2.0},
  {marca:"TERMOMAX",modelo:"Inox Power – IP 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.0},
  {marca:"TERMOMAX",modelo:"Inox Power – IP 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.5},
  {marca:"TERMOMAX",modelo:"Inox Power – IP 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.7},
  {marca:"TERMOMAX",modelo:"Inox Power – IP 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:2.0},
  {marca:"TERMOMAX",modelo:"MAX VÁCUO - 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:171.3,eficiencia:68.9,classificacao:"B",area:2.3},
  {marca:"TERMOMAX",modelo:"MAX VÁCUO - 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:225.1,eficiencia:68.9,classificacao:"B",area:3.0},
  {marca:"TERMOMAX",modelo:"MAX VÁCUO - 25",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:279.6,eficiencia:68.9,classificacao:"B",area:3.7},
  {marca:"TERMOMAX",modelo:"MAX VÁCUO - 30",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:332.7,eficiencia:68.9,classificacao:"B",area:4.5},
  {marca:"TERMOMAX",modelo:"Ultra Supreme – US 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:102.3,eficiencia:72.6,classificacao:"A",area:1.0},
  {marca:"TERMOMAX",modelo:"Ultra Supreme – US 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:153.3,eficiencia:72.6,classificacao:"A",area:1.5},
  {marca:"TERMOMAX",modelo:"Ultra Supreme – US 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:173.8,eficiencia:72.6,classificacao:"A",area:1.7},
  {marca:"TERMOMAX",modelo:"Ultra Supreme – US 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:204.5,eficiencia:72.6,classificacao:"A",area:2.0},
  {marca:"TERMOSOL",modelo:"Inox Power – IP 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.0},
  {marca:"TERMOSOL",modelo:"Inox Power – IP 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.5},
  {marca:"TERMOSOL",modelo:"Inox Power – IP 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:1.7},
  {marca:"TERMOSOL",modelo:"Inox Power – IP 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:83.9,eficiencia:60.8,classificacao:"A",area:2.0},
  {marca:"TERMOSOL",modelo:"Ultra Supreme – US 10",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:102.3,eficiencia:72.6,classificacao:"A",area:1.0},
  {marca:"TERMOSOL",modelo:"Ultra Supreme – US 15",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:153.3,eficiencia:72.6,classificacao:"A",area:1.5},
  {marca:"TERMOSOL",modelo:"Ultra Supreme – US 17",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:173.8,eficiencia:72.6,classificacao:"A",area:1.7},
  {marca:"TERMOSOL",modelo:"Ultra Supreme – US 20",fornecedor:"Termomax Aquecedor Solar Ltda. EPP",producao:204.5,eficiencia:72.6,classificacao:"A",area:2.0},
  {marca:"TERMOTRANS",modelo:"TTC 1,00 x 1,00",fornecedor:"Assenco Aquecedores e Sistemas Eireli",producao:69.4,eficiencia:50.3,classificacao:"C",area:1.0},
  {marca:"TERMOTRANS",modelo:"TTC 1,40 x 1,00",fornecedor:"Assenco Aquecedores e Sistemas Eireli",producao:97.2,eficiencia:50.3,classificacao:"C",area:1.4},
  {marca:"TERMOTRANS",modelo:"TTC 1,50 x 1,00",fornecedor:"Assenco Aquecedores e Sistemas Eireli",producao:104.1,eficiencia:50.3,classificacao:"C",area:1.5},
  {marca:"TERMOTRANS",modelo:"TTC 1,70 x 1,00",fornecedor:"Assenco Aquecedores e Sistemas Eireli",producao:118.0,eficiencia:50.3,classificacao:"C",area:1.7},
  {marca:"TERMOTRANS",modelo:"TTC 2,00 x 1,00",fornecedor:"Assenco Aquecedores e Sistemas Eireli",producao:138.8,eficiencia:50.3,classificacao:"C",area:2.0},
  {marca:"Thermoset",modelo:"THS 1.0",fornecedor:"Heliotek Termotecnologia Ltda.",producao:87.3,eficiencia:63.0,classificacao:"A",area:1.0},
  {marca:"Thermoset",modelo:"THS 1.5",fornecedor:"Heliotek Termotecnologia Ltda.",producao:130.6,eficiencia:63.0,classificacao:"A",area:1.5},
  {marca:"Thermoset",modelo:"THS 2.0",fornecedor:"Heliotek Termotecnologia Ltda.",producao:192.0,eficiencia:69.1,classificacao:"A",area:2.0},
  {marca:"Topsol",modelo:"Topsol 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:164.5,eficiencia:61.5,classificacao:"A",area:2.0},
  {marca:"Topsol",modelo:"Topsol I Inox 2,00 m²",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:157.8,eficiencia:59.3,classificacao:"B",area:2.0},
  {marca:"Topsol",modelo:"Topsol Mini",fornecedor:"Soletrol Indústria e Comércio Ltda.",producao:78.8,eficiencia:60.1,classificacao:"B",area:1.0},
  {marca:"Ubersol Aquecedores",modelo:"COLETOR A VÁCUO 15 TUBOS",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:195.4,eficiencia:59.9,classificacao:"A",area:2.3},
  {marca:"Ubersol Aquecedores",modelo:"COLETOR A VÁCUO 20 TUBOS",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:255.9,eficiencia:59.9,classificacao:"A",area:3.0},
  {marca:"Ubersol Aquecedores",modelo:"COLETOR A VÁCUO 25 TUBOS",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:316.8,eficiencia:59.9,classificacao:"A",area:3.7},
  {marca:"Ubersol Aquecedores",modelo:"COLETOR A VÁCUO 30 TUBOS",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:377.7,eficiencia:59.9,classificacao:"A",area:4.5},
  {marca:"Unisol Aquecedores Solares",modelo:"COLETOR A VÁCUO 15 TUBOS",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:195.4,eficiencia:59.9,classificacao:"A",area:2.3},
  {marca:"Unisol Aquecedores Solares",modelo:"COLETOR A VÁCUO 20 TUBOS",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:255.9,eficiencia:59.9,classificacao:"A",area:3.0},
  {marca:"Unisol Aquecedores Solares",modelo:"COLETOR A VÁCUO 25 TUBOS",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:316.8,eficiencia:59.9,classificacao:"A",area:3.7},
  {marca:"Unisol Aquecedores Solares",modelo:"COLETOR A VÁCUO 30 TUBOS",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:377.7,eficiencia:59.9,classificacao:"A",area:4.5},
  {marca:"Unisol Aquecedores Solares",modelo:"TURBO 1000",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:86.0,eficiencia:62.4,classificacao:"A",area:1.0},
  {marca:"Unisol Aquecedores Solares",modelo:"TURBO 1500",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:129.1,eficiencia:62.4,classificacao:"A",area:1.5},
  {marca:"Unisol Aquecedores Solares",modelo:"TURBO 1700",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:146.2,eficiencia:62.4,classificacao:"A",area:1.7},
  {marca:"Unisol Aquecedores Solares",modelo:"TURBO 2000",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:172.1,eficiencia:62.4,classificacao:"A",area:2.0},
  {marca:"Unisol Aquecedores Solares",modelo:"UNI 1000",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:77.1,eficiencia:56.1,classificacao:"B",area:1.0},
  {marca:"Unisol Aquecedores Solares",modelo:"UNI 1500",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:115.9,eficiencia:56.1,classificacao:"B",area:1.5},
  {marca:"Unisol Aquecedores Solares",modelo:"UNI 1700",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:131.3,eficiencia:56.1,classificacao:"B",area:1.7},
  {marca:"Unisol Aquecedores Solares",modelo:"UNI 2000",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:154.6,eficiencia:56.1,classificacao:"B",area:2.0},
  {marca:"Unisol Aquecedores Solares",modelo:"UNINOX 1000",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:76.4,eficiencia:55.8,classificacao:"B",area:1.0},
  {marca:"Unisol Aquecedores Solares",modelo:"UNINOX 1500",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:115.4,eficiencia:55.8,classificacao:"B",area:1.5},
  {marca:"Unisol Aquecedores Solares",modelo:"UNINOX 1700",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:130.7,eficiencia:55.8,classificacao:"B",area:1.7},
  {marca:"Unisol Aquecedores Solares",modelo:"UNINOX 2000",fornecedor:"Unisol Aquecedores Solares Ltda.",producao:153.9,eficiencia:55.8,classificacao:"B",area:2.0},
  {marca:"VIASOL",modelo:"VS-C1000",fornecedor:"Viasol Ind. e Com. de Aquecedores Solar Ltda.",producao:66.8,eficiencia:53.8,classificacao:"B",area:0.9},
  {marca:"VIASOL",modelo:"VS-C1500",fornecedor:"Viasol Ind. e Com. de Aquecedores Solar Ltda.",producao:103.5,eficiencia:53.8,classificacao:"B",area:1.4},
  {marca:"VIASOL",modelo:"VS-C1700",fornecedor:"Viasol Ind. e Com. de Aquecedores Solar Ltda.",producao:118.9,eficiencia:53.8,classificacao:"B",area:1.6},
  {marca:"VIASOL",modelo:"VS-C2000",fornecedor:"Viasol Ind. e Com. de Aquecedores Solar Ltda.",producao:138.0,eficiencia:53.8,classificacao:"B",area:1.9},
  {marca:"VIASOL",modelo:"VS-MAX1000",fornecedor:"Viasol Ind. e Com. de Aquecedores Solar Ltda.",producao:74.4,eficiencia:59.0,classificacao:"A",area:0.9},
  {marca:"VIASOL",modelo:"VS-MAX1500",fornecedor:"Viasol Ind. e Com. de Aquecedores Solar Ltda.",producao:113.7,eficiencia:59.0,classificacao:"A",area:1.4},
  {marca:"VIASOL",modelo:"VS-MAX1700",fornecedor:"Viasol Ind. e Com. de Aquecedores Solar Ltda.",producao:130.7,eficiencia:59.0,classificacao:"A",area:1.6},
  {marca:"VIASOL",modelo:"VS-MAX2000",fornecedor:"Viasol Ind. e Com. de Aquecedores Solar Ltda.",producao:151.7,eficiencia:59.0,classificacao:"A",area:1.9},
  {marca:"VIASOL ENERGIA SOLAR",modelo:"15 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:188.8,eficiencia:77.2,classificacao:"A",area:2.3},
  {marca:"VIASOL ENERGIA SOLAR",modelo:"20 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:245.9,eficiencia:77.2,classificacao:"A",area:3.0},
  {marca:"VIASOL ENERGIA SOLAR",modelo:"25 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:307.1,eficiencia:77.2,classificacao:"A",area:3.8},
  {marca:"VIASOL ENERGIA SOLAR",modelo:"30 TUBOS BP",fornecedor:"Aquecedores Max Chama Ltda.",producao:365.1,eficiencia:77.2,classificacao:"A",area:4.5},
  {marca:"VIESSMANN",modelo:"VITOSOL 200-F SVE",fornecedor:"Clesse do Brasil, Captação, Controle e Cond. de Energia Ltda.",producao:240.4,eficiencia:74.0,classificacao:"A",area:2.5},
];

export const MARCAS_COLETOR: string[] = Array.from(new Set(COLETORES.map((c) => c.marca))).sort((a, b) => a.localeCompare(b, "pt-BR"));

export function modelosDaMarca(marca: string): Coletor[] {
  return COLETORES.filter((c) => c.marca === marca).sort((a, b) => a.modelo.localeCompare(b.modelo, "pt-BR"));
}

export function acharColetor(marca: string, modelo: string): Coletor | undefined {
  return COLETORES.find((c) => c.marca === marca && c.modelo === modelo);
}
